services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: db-dev
      MYSQL_ROOT_PASSWORD: changemeinprod!
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080